Add mutli-arch support for specifically tagged images

diff --git a/.github/workflows/build-and-push-image.yaml b/.github/workflows/build-and-push-image.yaml
--- a/.github/workflows/build-and-push-image.yaml
+++ b/.github/workflows/build-and-push-image.yaml
@@ -140,16 +140,12 @@ jobs:
       - name: Show git commit data
         uses: rlespinasse/git-commit-data-action@v1.x
 
-      - name: Build and push specifically tagged image
-        if: ${{ ! (inputs.image_tag == 'set_tag') }}
-        uses: whoan/docker-build-with-cache-action@v5
-        with:
-          image_tag: ${{ matrix.architecture }}-${{ inputs.image_tag }}
-          username: ${{ secrets.ECR_REGISTRY_USERNAME }}
-          password: ${{ secrets.ECR_REGISTRY_PASSWORD }}
-          registry: ${{ env.ECR_REGISTRY }}
-          image_name: ${{ env.IMAGE_NAME }}
-          build_extra_args: ${{ secrets.BUILD_ARGS }}
+      - name: Install manifest-tool
+        run: |
+          wget -O ./manifest-tool.tar.gz https://github.com/estesp/manifest-tool/releases/download/v${{ env.MANIFEST_TOOL_VERSION }}/binaries-manifest-tool-${{ env.MANIFEST_TOOL_VERSION }}.tar.gz
+          tar zxvf ./manifest-tool.tar.gz
+          mv ./manifest-tool-linux-${{ matrix.architecture }} ./manifest-tool
+          chmod +x ./manifest-tool
 
       - name: Build and push
         if: ${{ inputs.image_tag == 'set_tag' }}
@@ -187,14 +183,8 @@ jobs:
 
           docker push ${{ env.DOCKERHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.architecture }}-latest
 
-      - name: Install manifest-tool
-        run: |
-          wget -O ./manifest-tool.tar.gz https://github.com/estesp/manifest-tool/releases/download/v${{ env.MANIFEST_TOOL_VERSION }}/binaries-manifest-tool-${{ env.MANIFEST_TOOL_VERSION }}.tar.gz
-          tar zxvf ./manifest-tool.tar.gz
-          mv ./manifest-tool-linux-${{ matrix.architecture }} ./manifest-tool
-          chmod +x ./manifest-tool
-
       - name: Push multi-architecture image manifest to ECR
+        if: ${{ inputs.image_tag == 'set_tag' }}
         run: |
           (./manifest-tool \
             push from-args \
@@ -221,6 +211,31 @@ jobs:
           custom_tag: ${{ needs.set_tag.outputs.tag }}
           github_token: ${{ secrets.GH_PRIVATE_REPO_TOKEN }}
           tag_prefix: ''
+
+      # The following two steps are only used when a specific tag is passed as an input to this reusable workflow
+
+      - name: Build and push specifically tagged image
+        if: ${{ ! (inputs.image_tag == 'set_tag') }}
+        uses: whoan/docker-build-with-cache-action@v5
+        with:
+          image_tag: ${{ matrix.architecture }}-${{ inputs.image_tag }}
+          username: ${{ secrets.ECR_REGISTRY_USERNAME }}
+          password: ${{ secrets.ECR_REGISTRY_PASSWORD }}
+          registry: ${{ env.ECR_REGISTRY }}
+          image_name: ${{ env.IMAGE_NAME }}
+          build_extra_args: ${{ secrets.BUILD_ARGS }}
+
+      - name: Push specifically tagged multi-architecture image manifest to ECR
+        if: ${{ ! (inputs.image_tag == 'set_tag') }}
+        run: |
+          (./manifest-tool \
+            push from-args \
+            --platforms ${{ env.COMMA_SEPARATED_ARCHITECTURES }} \
+            --template ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:ARCH-${{ inputs.image_tag }} \
+            --target ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }} \
+          && ./manifest-tool \
+            inspect ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}) \
+          || echo "Can't push multi-arch image. This most likely means the builds for the other architectures are not yet complete."
 
       - name: Notify slack of a cancellation
         if: ${{ cancelled() && (matrix.architecture == 'amd64') && (inputs.image_tag == 'set_tag') }}
